#
# [Cpurge] - [Config]
#

messages:
  warning: "Построенный столб будет разрушен через минуту. Нажмите [ЛКМ] по столбу, чтобы отменить"
  postSaved: "Разрушение отменено"
  postRemoved: "Столб был разрушен"
settings:
  minHeight: 5
  removeTimeout: 60
  forgetTimeout: 300
  disableOnWorlds:
  - world1